Add info about the type of metric and expiry date on Metric Detail Page
mozilla/glean-dictionary pull request #103
Opened 2020-10-12 20:52 UTC by meghajain-1711

Fixes issue #100

Added type of Metric and Expiry Information below the Metric name and description.
The Metric type links to its documentation as well.

Example of ; never expires
![image](https://user-images.githubusercontent.com/59704142/95789119-8e148980-0cfa-11eb-8875-cd59447cd983.png)

Example of : expiry date to come
![image](https://user-images.githubusercontent.com/59704142/95789240-ccaa4400-0cfa-11eb-85bb-cb30f6ea2815.png)

Example of : expiry date gone past
![image](https://user-images.githubusercontent.com/59704142/95789317-f06d8a00-0cfa-11eb-984f-e93a7e1e5761.png)

@wlach your comments are welcome :)

2020-10-12 21:08 UTC, DawoodShahat commented
Hey @meghajain-1711 , I think you can add these changes to your previous PR [https://github.com/mozilla/glean-dictionary/pull/79](https://github.com/mozilla/glean-dictionary/pull/79) 

Because they are the same pages. 

You would want something like this that has the information like metric_type and metric_expiration date
![Screenshot 2020-10-13 at 2 04 02 AM](https://user-images.githubusercontent.com/19612755/95790231-6ae8da80-0cf8-11eb-924a-8db1bc05de2f.png)

You can put all the data in one place for a specific metric.

2020-10-13 15:22 UTC, wlach requested changes
> Hey @meghajain-1711 , I think you can add these changes to your previous PR #79
> ...

Yeah, strictly I would agree -- this would be in scope for #79. However, I'm also ok with landing this separately. There will definitely be many followups to all the pages at this early stage, as we figure out what to display and how to display it.

I'm ok to land this once the one issue I mention below is addressed.

2020-10-13 15:22 UTC, wlach commented on src/pages/MetricDetail.svelte
> +    return links[type] || sourceDocs;
This seems like a good approach to me, but there's no need to define the sourceDocs variable each time-- instead, try something like this:

```suggestion
    return `${sourceDocs}${links[type]}` || sourceDocs;
```

2020-10-13 15:43 UTC, meghajain-1711 commented
Hi @wlach Updated as per the request. It definitely made the codebase simpler :) 
Also , I have added a link to the params.app ie Application from which the metric was found. 

Let me know if it looks good now. 
![image](https://user-images.githubusercontent.com/59704142/95883836-ffa31500-0d98-11eb-8234-81dff22cc4ce.png)

2020-10-13 16:14 UTC, wlach approved these changes

2020-10-13 16:14 UTC, merged