Fix some metric pages
mozilla/glean-dictionary pull request #131
Opened 2020-10-19 05:03 UTC by DawoodShahat

This PR fixes #130

2020-10-19 05:20 UTC, mhmohona commented
These are Bugzilla links. see?  https://bugzilla.mozilla.org/show_bug.cgi?id=1556751

2020-10-19 05:28 UTC, DawoodShahat commented
Thanks @mhmohona I will update this in the next commit.

2020-10-20 19:18 UTC, wlach requested changes

2020-10-20 19:18 UTC, wlach commented on src/pages/MetricDetail.svelte
> +          </a>
While you're here, can you use the style @mhmohona used in #132? It's a little more descriptive to show the full URL.

(longer term we can come up with a better format for the bugs, but let's leave to later)

2020-10-21 13:40 UTC, wlach approved these changes

2020-10-21 13:41 UTC, merged