Render markdown in description fields (fixes #153)
mozilla/glean-dictionary pull request #155
Opened 2020-10-23 22:04 UTC by alvesitalo

### Pull Request checklist

- [x] The pull request has a descriptive title (and a reference to an issue it
      fixes, if applicable)
- [x] All tests and linter checks are passing
- [x] The pull request is free of merge conflicts

2020-10-26 21:08 UTC, wlach approved these changes
This looks great, I actually don't have any feedback. :) Merging as-is.

2020-10-26 21:13 UTC, wlach requested changes
Actually, sorry, there are some changes I'd request (it's been a long day).  With regard to ping descriptions, we should also use this component on this page: https://github.com/mozilla/glean-dictionary/blob/main/src/pages/PingDetail.svelte

Also, I think we need to apply this to more than just pings. For example, metrics might have markdown in their descriptions as well. See, for example:

http://localhost:5000/#!/apps/fenix/metrics/metrics.search_count

2020-10-26 21:13 UTC, wlach commented on src/components/PingDescription.svelte
> +<a href={`/apps/${app}/pings/${name}`}>{name}</a>
Should probably not include this by default, since in some cases (on the ping page) we may not show this.

2020-10-28 19:20 UTC, alvesitalo commented
Pings and metrics are having markdown in their descriptions now. In addition, the markdown is being rendered inline so pings will no longer have a <p> tag :tada:.

2020-10-28 19:31 UTC, wlach requested changes
Code looks good now, thanks!

Thinking about this a bit more, I think we should generalize this to a `Markdown` component and use [slots]((https://svelte.dev/tutorial/slots)), instead of hardcoding a description field . That way you could do something like this just about anywhere:

```svelte
<Markdown>
This my *markdown* text with a [link](https://mozilla.org)
</Markdown>
```

Do you mind making the modifications? After that, I'd be very happy to land.

2020-10-28 21:30 UTC, alvesitalo commented
I don't. I think It's a great idea.

2020-10-30 16:16 UTC, alvesitalo commented
Done! Markdown component is working, I just had to add a text var to work as a fallback for slot on StoryBook. Let me know if everything is OK.

2020-10-30 20:16 UTC, wlach approved these changes

2020-10-30 20:16 UTC, wlach commented on src/components/Markdown.svelte
> +</div>
Hmm, it's a bit unfortunate that this adds a hidden div to the document:

![image](https://user-images.githubusercontent.com/20569/97752546-8f9bcb00-1aca-11eb-8c9c-c5b01a52c428.png)

I offhand don't know of a better way of doing this though, and your solution does work well, so am inclined to merge.

2020-10-30 20:16 UTC, merged

2020-10-30 20:16 UTC, wlach commented
Awesome work @alvesitalo! Congratulations on getting this over line.