Restyle AppAlert (fixes #316)
mozilla/glean-dictionary pull request #324
Opened 2021-01-15 15:23 UTC by Iinh

This PR restyles AppAlert to fix #316. Right now the only type of Alert we need is "warning" for apps that are prototype, but I also added styling for "success" and "error" to make this component more usable in the future. 
 
### Pull Request checklist

- [ ] The pull request has a descriptive title (and a reference to an issue it
      fixes, if applicable)
- [ ] All tests and linter checks are passing
- [ ] The pull request is free of merge conflicts

2021-01-15 15:27 UTC, Iinh commented
Draft PR because I am dealing with a compiling error with Storybook. It seems like Storybook doesn't understand the <svelte:component> tag that is used in AppAlert. Looking for a first pass feedback on the restyling @wlach while I'm trying to figure how I can reconfigure Storybook to work with Svelte, yet again 😅

2021-01-15 17:41 UTC, wlach requested changes
Looks good (minus the storybook issues). I have some minor feedback

2021-01-18 19:49 UTC, wlach approved these changes

2021-01-18 19:50 UTC, merged

2021-01-18 19:50 UTC, wlach commented
Thanks @Iinh!