Add Sourcegraph links for metrics not indexed by Searchfox
mozilla/glean-dictionary pull request #468
Opened 2021-03-17 05:45 UTC by jcads

Fixes #404 

### Pull Request checklist

- [x] The pull request has a descriptive title (and a reference to an issue it
      fixes, if applicable)
- [x] All tests and linter checks are passing
- [x] The pull request is free of merge conflicts

2021-03-17 13:43 UTC, wlach requested changes
Thanks @jcads! Just have a few requests for changes before this lands.

2021-03-17 13:43 UTC, wlach commented on src/formatters/searchfox.js
> +const sourcegraphMap = {
Could you rename this file to something like codesearch.js?

2021-03-17 13:43 UTC, wlach commented on src/formatters/searchfox.js
>    // Generate all possible casings for a Searchfox query:
```suggestion
  // Generate all possible casings for a search query:
```

2021-03-17 13:43 UTC, wlach commented on src/formatters/searchfox.js
> +  return (
Let's check to make sure there is an entry for this app in sourcegraph, just as we do above for searchfox.

There may be some cases where we don't have a code search service for a repository.

2021-03-17 13:43 UTC, wlach commented on src/formatters/searchfox.js
> +export const getMetricLink = (app, metric) => {
```suggestion
export const getCodeSearchLink = (app, metric) => {
```

2021-03-17 13:43 UTC, wlach commented on src/data/schemas.js
> +      return getMetricLink(appName, metricId);
Could you rename this entry to `Code Search`? Seems more intuitive to me.

2021-03-18 15:35 UTC, wlach approved these changes
Thanks for this!

The only bug I can see is that it seems like we're still showing the "code search" option (with no link) even when it's unavailable. e.g. https://deploy-preview-468--glean-dictionary-dev.netlify.app/apps/bergamot/metrics/errors_marian

![image](https://user-images.githubusercontent.com/20569/111652714-ade63700-87dd-11eb-8997-c1f78208c9ee.png)

However that seems like an old issue, so I'm going to merge this as-is. 

@jcads would you be interested in investigating that as a followup?

2021-03-18 15:35 UTC, merged

2021-03-18 15:55 UTC, jcads commented
You're welcome, @wlach! :tada: 

As for the bug, I'll gladly look into that.

2021-03-18 17:16 UTC, jcads commented
I did some digging and I think it's because `bergamot` has just recently been added to https://probeinfo.telemetry.mozilla.org/v2/glean/app-listings, where the glean-dictionary data is pulled from. Therefore, it wasn't added to `codesearch.js` to be indexed.

And just a sidenote: bergamot can't be currently indexed on both searchfox and sourcegraph, so adding it in `codesearch.js` will not fix the bug.

Should the "code search" option be removed when the link is unavailable?

2021-03-18 22:15 UTC, wlach commented
> And just a sidenote: bergamot can't be currently indexed on both searchfox and sourcegraph, so adding it in `codesearch.js` will not fix the bug.

Right :) I asked about this on the #github-admin channel on Matrix today. I think searchgraph is not yet indexing the `mozilla-extensions` organization. I can ping them later about this.
 
> Should the "code search" option be removed when the link is unavailable?

I think it would be better to just say something like `Unavailable: no search index specified for this application.`. That way people know the reason why it's missing.

2021-03-19 04:08 UTC, jcads commented
> I think it would be better to just say something like Unavailable: no search index specified for this application.. That way people know the reason why it's missing.

Got it! Opening a new issue.